apiVersion: v1
kind: Service
metadata:
  name: voting-service
  labels:
    name: voting-service
    app: sample-voting-app
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  # to access voting application externally the port need to be expose 80 :80
  selector:
    name: voting-app-pod
    app: sample-voting-app
